[project]
name = "mcts-mate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tezcayotl", email = "escuderoenriquez2210@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mcts-mate = "mcts_mate:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
]
